// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: protos/verify.proto

package proto_buffers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyPhoneNumberData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber string `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Otp         string `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	Flow        string `protobuf:"bytes,3,opt,name=flow,proto3" json:"flow,omitempty"`
}

func (x *VerifyPhoneNumberData) Reset() {
	*x = VerifyPhoneNumberData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_verify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyPhoneNumberData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPhoneNumberData) ProtoMessage() {}

func (x *VerifyPhoneNumberData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_verify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPhoneNumberData.ProtoReflect.Descriptor instead.
func (*VerifyPhoneNumberData) Descriptor() ([]byte, []int) {
	return file_protos_verify_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyPhoneNumberData) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *VerifyPhoneNumberData) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

func (x *VerifyPhoneNumberData) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

type VerifyPhoneNumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *VerifyPhoneNumberResponse) Reset() {
	*x = VerifyPhoneNumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_verify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyPhoneNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPhoneNumberResponse) ProtoMessage() {}

func (x *VerifyPhoneNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_verify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPhoneNumberResponse.ProtoReflect.Descriptor instead.
func (*VerifyPhoneNumberResponse) Descriptor() ([]byte, []int) {
	return file_protos_verify_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyPhoneNumberResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_protos_verify_proto protoreflect.FileDescriptor

var file_protos_verify_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x62, 0x75, 0x66,
	0x66, 0x65, 0x72, 0x73, 0x22, 0x5f, 0x0a, 0x15, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a,
	0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x6f, 0x74, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x74,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x66, 0x6c, 0x6f, 0x77, 0x22, 0x33, 0x0a, 0x19, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x73, 0x0a, 0x11, 0x55, 0x73,
	0x65, 0x72, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x5e, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x24, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x73, 0x2e, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x44,
	0x61, 0x74, 0x61, 0x1a, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x62, 0x75, 0x66, 0x66,
	0x65, 0x72, 0x73, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75,
	0x74, 0x68, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_verify_proto_rawDescOnce sync.Once
	file_protos_verify_proto_rawDescData = file_protos_verify_proto_rawDesc
)

func file_protos_verify_proto_rawDescGZIP() []byte {
	file_protos_verify_proto_rawDescOnce.Do(func() {
		file_protos_verify_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_verify_proto_rawDescData)
	})
	return file_protos_verify_proto_rawDescData
}

var file_protos_verify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_verify_proto_goTypes = []interface{}{
	(*VerifyPhoneNumberData)(nil),     // 0: proto_buffers.VerifyPhoneNumberData
	(*VerifyPhoneNumberResponse)(nil), // 1: proto_buffers.VerifyPhoneNumberResponse
}
var file_protos_verify_proto_depIdxs = []int32{
	0, // 0: proto_buffers.UserVerifyService.VerifyUser:input_type -> proto_buffers.VerifyPhoneNumberData
	1, // 1: proto_buffers.UserVerifyService.VerifyUser:output_type -> proto_buffers.VerifyPhoneNumberResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_verify_proto_init() }
func file_protos_verify_proto_init() {
	if File_protos_verify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_verify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyPhoneNumberData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_verify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyPhoneNumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_verify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_verify_proto_goTypes,
		DependencyIndexes: file_protos_verify_proto_depIdxs,
		MessageInfos:      file_protos_verify_proto_msgTypes,
	}.Build()
	File_protos_verify_proto = out.File
	file_protos_verify_proto_rawDesc = nil
	file_protos_verify_proto_goTypes = nil
	file_protos_verify_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserVerifyServiceClient is the client API for UserVerifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserVerifyServiceClient interface {
	VerifyUser(ctx context.Context, in *VerifyPhoneNumberData, opts ...grpc.CallOption) (*VerifyPhoneNumberResponse, error)
}

type userVerifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserVerifyServiceClient(cc grpc.ClientConnInterface) UserVerifyServiceClient {
	return &userVerifyServiceClient{cc}
}

func (c *userVerifyServiceClient) VerifyUser(ctx context.Context, in *VerifyPhoneNumberData, opts ...grpc.CallOption) (*VerifyPhoneNumberResponse, error) {
	out := new(VerifyPhoneNumberResponse)
	err := c.cc.Invoke(ctx, "/proto_buffers.UserVerifyService/VerifyUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserVerifyServiceServer is the server API for UserVerifyService service.
type UserVerifyServiceServer interface {
	VerifyUser(context.Context, *VerifyPhoneNumberData) (*VerifyPhoneNumberResponse, error)
}

// UnimplementedUserVerifyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserVerifyServiceServer struct {
}

func (*UnimplementedUserVerifyServiceServer) VerifyUser(context.Context, *VerifyPhoneNumberData) (*VerifyPhoneNumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyUser not implemented")
}

func RegisterUserVerifyServiceServer(s *grpc.Server, srv UserVerifyServiceServer) {
	s.RegisterService(&_UserVerifyService_serviceDesc, srv)
}

func _UserVerifyService_VerifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPhoneNumberData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserVerifyServiceServer).VerifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_buffers.UserVerifyService/VerifyUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserVerifyServiceServer).VerifyUser(ctx, req.(*VerifyPhoneNumberData))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserVerifyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto_buffers.UserVerifyService",
	HandlerType: (*UserVerifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyUser",
			Handler:    _UserVerifyService_VerifyUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/verify.proto",
}
